//! Black-box cross-validation fixtures.
//!
//! GSM 06.10 §5.2 / §5.3 define a fully deterministic fixed-point
//! pipeline, so ANY two conformant implementations must agree
//! byte-for-byte on the encode direction and sample-for-sample on the
//! decode direction. The ETSI §6.3 binary test sequences are not
//! staged under `docs/audio/gsm/`, so this suite pins the next best
//! thing: reference bytes produced by independent codec binaries
//! invoked as **opaque black boxes** (see `tests/fixtures/README.md`
//! for the exact generation commands).
//!
//! * `tests/fixtures/blackbox_*.gsm` hold the black-box encoder's
//!   output for four deterministic PCM programs regenerated by this
//!   file (integer-only synthesis — bit-identical on every platform).
//!   The encoder tests require our §5.2 chain to reproduce those
//!   bytes **exactly**, frame by frame, through the de-facto 33-byte
//!   `.gsm` byte-frame packer.
//! * The decoder tests decode the same fixtures with our §5.3 chain
//!   and require the output PCM to match the digest of an
//!   *independent* black-box decode of the identical bytes.
//!
//! Coverage notes:
//!
//! * `quiet` never engages the §5.2.4 dynamic scaling
//!   (`smax < 2048`); `loud` and `hostile` engage it every frame —
//!   the `hostile` program holds full-scale squares, max-slew
//!   alternation, an `i16::MIN` plateau, impulse trains on a DC
//!   offset, and a loud chirp, driving the §5.1 saturation
//!   arithmetic (Table 6.2 overflow points) end-to-end.
//! * `rand` is amplitude-swept LCG noise whose loudest step requests
//!   ±60000 and clips to the i16 rails — the §6.3.1 "critical
//!   path"-style material where a second black-box decoder binary is
//!   known to disagree with the reference decode (see the fixtures
//!   README); the digest pinned here is the reference decoder's.

use oxideav_gsm::{DecoderState, EncoderState, UnpackedFrame, GSM_BYTE_FRAME_LEN};

const FRAME: usize = 160;

// ─── Deterministic PCM programs (integer-only, platform-exact) ───

/// Two triangle carriers (~311 Hz / ~1123 Hz) under a five-step
/// per-frame amplitude staircase `base + step * (frame % 5)`.
fn gen_amp(frames: usize, base: i64, step: i64) -> Vec<i16> {
    let mut out = Vec::with_capacity(frames * FRAME);
    let mut phase1: i64 = 0;
    let mut phase2: i64 = 0;
    for n in 0..(frames * FRAME) as i64 {
        phase1 = (phase1 + 311 * 65536 / 8000) % 65536;
        phase2 = (phase2 + 1123 * 65536 / 8000) % 65536;
        let tri = |p: i64| -> i64 {
            if p < 32768 {
                p - 16384
            } else {
                49152 - p
            }
        };
        let am = base + step * ((n / 160) % 5);
        let s = (tri(phase1) * am / 16384) + (tri(phase2) * am / 3 / 16384);
        out.push(s.clamp(-32768, 32767) as i16);
    }
    out
}

/// Hostile extremes: slow full-scale square, max-slew alternation,
/// `i16::MIN` plateau, impulse train on a DC offset, loud chirp.
fn gen_hostile() -> Vec<i16> {
    let mut pcm: Vec<i16> = Vec::new();
    for n in 0..(40 * FRAME) as i64 {
        let seg = n / (8 * FRAME as i64) % 5;
        let v: i32 = match seg {
            0 => {
                if (n / 10) % 2 == 0 {
                    32767
                } else {
                    -32768
                }
            }
            1 => {
                if n % 2 == 0 {
                    32767
                } else {
                    -32768
                }
            }
            2 => -32768,
            3 => {
                if n % 37 == 0 {
                    32767
                } else {
                    -20000
                }
            }
            _ => {
                let rate = 1 + (n % 1600) / 100;
                let ph = (n * rate) % 200;
                (((ph - 100) * 655).clamp(-32768, 32767)) as i32
            }
        };
        pcm.push(v as i16);
    }
    pcm
}

/// Amplitude-swept LCG noise; the ±60000 step clips at the rails.
fn gen_rand() -> Vec<i16> {
    let mut seed: u32 = 0x2468_ACE1;
    let mut out = Vec::with_capacity(300 * FRAME);
    for f in 0..300u64 {
        let amp: i64 = [50, 500, 3000, 12000, 32767, 60000][(f % 6) as usize];
        for _ in 0..FRAME {
            seed = seed.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            let v = ((seed >> 8) as i64 % (2 * amp + 1)) - amp;
            out.push(v.clamp(-32768, 32767) as i16);
        }
    }
    out
}

// ─── Digest (FNV-1a 64 over the little-endian PCM bytes) ───

fn fnv1a64_pcm(pcm: &[i16]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &s in pcm {
        for b in s.to_le_bytes() {
            h ^= b as u64;
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    h
}

// ─── Harness ───

fn encode_all(pcm: &[i16]) -> Vec<u8> {
    let mut enc = EncoderState::new();
    let mut out = Vec::with_capacity(pcm.len() / FRAME * GSM_BYTE_FRAME_LEN);
    for chunk in pcm.chunks_exact(FRAME) {
        let mut buf = [0i16; FRAME];
        buf.copy_from_slice(chunk);
        let frame = enc.encode_frame(&buf);
        out.extend_from_slice(&frame.to_gsm_byte_frame());
    }
    out
}

fn decode_all(gsm: &[u8]) -> Vec<i16> {
    let mut dec = DecoderState::new();
    let mut out = Vec::with_capacity(gsm.len() / GSM_BYTE_FRAME_LEN * FRAME);
    for fb in gsm.chunks_exact(GSM_BYTE_FRAME_LEN) {
        let f = UnpackedFrame::from_gsm_byte_frame(fb).expect("fixture frame must parse");
        out.extend_from_slice(&dec.decode_frame(&f));
    }
    out
}

fn assert_encoder_matches(pcm: &[i16], fixture: &[u8], name: &str) {
    assert_eq!(
        fixture.len() % GSM_BYTE_FRAME_LEN,
        0,
        "{name}: fixture must be whole 33-byte frames"
    );
    assert_eq!(
        pcm.len() / FRAME,
        fixture.len() / GSM_BYTE_FRAME_LEN,
        "{name}: frame-count mismatch between PCM program and fixture"
    );
    let ours = encode_all(pcm);
    // Compare frame-by-frame for a readable failure location.
    for (i, (a, b)) in ours
        .chunks_exact(GSM_BYTE_FRAME_LEN)
        .zip(fixture.chunks_exact(GSM_BYTE_FRAME_LEN))
        .enumerate()
    {
        assert_eq!(a, b, "{name}: encoder output differs at frame {i}");
    }
}

// ─── Encoder: byte-exact against the black-box encoder ───

#[test]
fn encoder_bit_exact_blackbox_quiet() {
    // §5.2.4 dynamic scaling never engages (smax < 2048).
    assert_encoder_matches(
        &gen_amp(200, 1024, 512),
        include_bytes!("fixtures/blackbox_quiet.gsm"),
        "quiet",
    );
}

#[test]
fn encoder_bit_exact_blackbox_loud() {
    // §5.2.4 dynamic scaling engages every frame; regression cover
    // for the §5.2.4 rescale-into-§5.2.10 conformance fix.
    assert_encoder_matches(
        &gen_amp(200, 8192, 2048),
        include_bytes!("fixtures/blackbox_loud.gsm"),
        "loud",
    );
}

#[test]
fn encoder_bit_exact_blackbox_hostile() {
    assert_encoder_matches(
        &gen_hostile(),
        include_bytes!("fixtures/blackbox_hostile.gsm"),
        "hostile",
    );
}

#[test]
fn encoder_bit_exact_blackbox_rand() {
    assert_encoder_matches(
        &gen_rand(),
        include_bytes!("fixtures/blackbox_rand.gsm"),
        "rand",
    );
}

// ─── Decoder: sample-exact against the independent black-box decode ───

#[test]
fn decoder_sample_exact_blackbox_quiet() {
    let pcm = decode_all(include_bytes!("fixtures/blackbox_quiet.gsm"));
    assert_eq!(pcm.len(), 200 * FRAME);
    assert_eq!(fnv1a64_pcm(&pcm), 0x645C_67C8_EECD_64A5);
}

#[test]
fn decoder_sample_exact_blackbox_loud() {
    let pcm = decode_all(include_bytes!("fixtures/blackbox_loud.gsm"));
    assert_eq!(pcm.len(), 200 * FRAME);
    assert_eq!(fnv1a64_pcm(&pcm), 0x88FA_3B64_F1F8_CA3C);
}

#[test]
fn decoder_sample_exact_blackbox_hostile() {
    let pcm = decode_all(include_bytes!("fixtures/blackbox_hostile.gsm"));
    assert_eq!(pcm.len(), 40 * FRAME);
    assert_eq!(fnv1a64_pcm(&pcm), 0xA084_5E7B_5CF2_1871);
}

#[test]
fn decoder_sample_exact_blackbox_rand() {
    let pcm = decode_all(include_bytes!("fixtures/blackbox_rand.gsm"));
    assert_eq!(pcm.len(), 300 * FRAME);
    assert_eq!(fnv1a64_pcm(&pcm), 0x9F59_2FC0_68F4_C105);
}

// ─── Container sanity over the fixture corpus ───

/// Every black-box frame carries the 0xD marker nibble and round-trips
/// through our byte-frame pack/unpack byte-identically — the container
/// layout the crate implements is exactly the one the black boxes
/// speak.
#[test]
fn fixtures_all_frames_carry_marker_and_roundtrip() {
    for (name, bytes) in [
        ("quiet", &include_bytes!("fixtures/blackbox_quiet.gsm")[..]),
        ("loud", &include_bytes!("fixtures/blackbox_loud.gsm")[..]),
        (
            "hostile",
            &include_bytes!("fixtures/blackbox_hostile.gsm")[..],
        ),
        ("rand", &include_bytes!("fixtures/blackbox_rand.gsm")[..]),
    ] {
        for (i, fb) in bytes.chunks_exact(GSM_BYTE_FRAME_LEN).enumerate() {
            assert_eq!(fb[0] >> 4, 0xD, "{name} frame {i}: marker nibble");
            let f = UnpackedFrame::from_gsm_byte_frame(fb).unwrap();
            assert_eq!(
                f.to_gsm_byte_frame().as_slice(),
                fb,
                "{name} frame {i}: byte-frame round-trip"
            );
        }
    }
}

/// §5.3.7 output shaping holds over every decoded fixture sample
/// (13-bit output: the three low bits are zero).
#[test]
fn fixtures_decode_respects_output_shaping() {
    for bytes in [
        &include_bytes!("fixtures/blackbox_quiet.gsm")[..],
        &include_bytes!("fixtures/blackbox_loud.gsm")[..],
        &include_bytes!("fixtures/blackbox_hostile.gsm")[..],
        &include_bytes!("fixtures/blackbox_rand.gsm")[..],
    ] {
        for s in decode_all(bytes) {
            assert_eq!(s & 7, 0, "§5.3.7: low three bits must be zero");
        }
    }
}
